export enum PageErrorType {
  OPPORTUNITY_NOT_FOUND = 'OPPORTUNITY_NOT_FOUND',
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
  ACCESS_POINT_NOT_FOUND = 'ACCESS_POINT_NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
}
