@startuml ced_er_diagram

entity Organization {
    * id: uuid
    --
    * external_id: uuid
    * name: string
    * created_at: timestamp
    * updated_at: timestamp
}

entity Place {
    * id: uuid
    --
    * organization_id: uuid <<FK>>
    * name: string
    * type: enum("online","offline")
    * created_at: timestamp
    * updated_at: timestamp
}

entity Website {
    * id: uuid
    --
    * place_id: uuid <<FK>>
    * url: string
    * created_at: timestamp
    * updated_at: timestamp
}

entity Address {
    * id: uuid
    --
    * place_id: uuid <<FK>>
    * street: string
    * city: string
    * state: string
    * postal_code: string
    * country: string
    * created_at: timestamp
    * updated_at: timestamp
}

entity SupportContact {
    * id: uuid
    --
    * place_id: uuid <<FK>>
    * type: enum("email","phone","website")
    * value: string
    * created_at: timestamp
    * updated_at: timestamp
}

entity OpportunityPlace {
    * opportunity_id: uuid <<FK>>
    * place_id: uuid <<FK>>
}

entity Opportunity {
    * id: uuid
    --
    * organization_id: uuid <<FK>>
    * status: enum("draft","published","suspended","archived")
    * date_from: date
    date_to: date
    url: string
    * created_at: timestamp
    * updated_at: timestamp
}

entity EligibleBenefit {
    * id: uuid
    --
    * opportunity_id: uuid <<FK>>
    * value: integer
    * type: enum("percentual","absolute")
    * created_at: timestamp
    * updated_at: timestamp
}

entity CaregiverBenefit {
    * id: uuid
    --
    * opportunity_id: uuid <<FK>>
    * value: integer
    * type: enum("percentual","absolute")
    * created_at: timestamp
    * updated_at: timestamp
}

entity LocalizedMetadata {
    * id: uuid
    --
    * opportunity_id: uuid <<FK>>
    * key: enum("name","description","condition","type","category")
    * language: enum("en","fr","de","sl","it")
    * value: string
    * created_at: timestamp
    * updated_at: timestamp
}

Organization ||--|{ Place
Organization ||--|{ Opportunity
Place ||--o| Address
Place ||--o| Website
Place ||--|{ SupportContact
Place ||--|{ OpportunityPlace
Opportunity ||--|{ OpportunityPlace
LocalizedMetadata }|--|| Opportunity
Opportunity ||--|| EligibleBenefit
Opportunity ||--o| CaregiverBenefit

@enduml