name: Deploy Portal FE to Azure Static Web App

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - "apps/ced-portal-fe/**"
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - closed
        branches:
            - main
        paths:
            - "apps/ced-portal-fe/**"

jobs:
    deploy_portal_fe:
        uses: pagopa/dx/.github/workflows/release-azure-staticapp-v1.yaml@main
        name: Deploy Portal FE
        secrets: inherit
        with:
            workspace_name: ced-portal-fe
            output_dir: dist
            static_web_app_name: ced-p-itn-portal-fe-stapp-01
            resource_group_name: ced-p-itn-rg-01
            environment: app-prod
            use_private_agent: true
            use_labels: false
