name: Deploy CED Browser BE to Azure Container App

permissions:
  contents: read
  attestations: write
  packages: write
  id-token: write

on:
  workflow_dispatch: {}

jobs:
  deploy_ced_browser_be:
    uses: pagopa/dx/.github/workflows/release-azure-containerapp-v1.yaml@main
    name: Deploy CED Browser BE
    secrets: inherit
    with:
      # The dockerfile_context and dockerfile_path are not specified because the defaults are './' and './Dockerfile' respectively.
      container_app: ced-p-itn-browser-be-ca-01
      resource_group_name: ced-p-itn-rg-01
      environment: app-prod
      docker_image_description: "CED Browser Backend - Backend service for the
        CIT's CED browser to view opportunities"
      docker_image_name: pagopa/ced-browser-be
      build_args: "APP_NAME=ced-browser-be"
