name: Deploy CED Browser FE to Azure Static Web App

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - "apps/ced-browser-fe/**"
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - closed
        branches:
            - main
        paths:
            - "apps/ced-browser-fe/**"

jobs:
    deploy_ced_browser_fe:
        uses: pagopa/dx/.github/workflows/release-azure-staticapp-v1.yaml@723b8233cd9c48bac7cc9e796471d4e12d4f8e5c # main
        name: Deploy CED Browser FE
        secrets: inherit
        with:
            workspace_name: ced-browser-fe
            output_dir: dist
            static_web_app_name: ced-p-weu-browser-fe-stapp-01
            resource_group_name: ced-p-itn-rg-01
            environment: app-prod
            use_private_agent: true
            use_labels: false
