name: Test migrate DB

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch: {}

jobs:
  run_migrations:
    name: Run DB Migrations
    runs-on: [self-hosted, prod]
    environment: app-prod-cd
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.0.4
        with:
          node-version-file: ".node-version"

      - name: Install pnpm
        run: corepack enable && corepack prepare

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: |
          pnpm build --filter="ced-portal-be"

      - name: Run migrations
        env:
          POSTGRES_HOST: ${{ secrets.CED_POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.CED_POSTGRES_PORT }}
          POSTGRES_USER: ${{ secrets.CED_POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.CED_POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.CED_POSTGRES_DB }}
          POSTGRES_DB_TEST: ${{ secrets.CED_POSTGRES_DB_TEST }}
          POSTGRES_SSL: "true"
        run: pnpm --filter ced-portal-be migrate:cloud:test
