name: Run Portal BE DB Migrations

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch: {}

jobs:
  run_migrations:
    name: Run DB Migrations
    runs-on: [ self-hosted, prod ]
    environment: app-prod-cd
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"

      - name: Install pnpm
        run: corepack enable && corepack prepare

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: |
          pnpm --filter @pagopa/io-core-domain build
          pnpm --filter @pagopa/io-core-adapter-fastify build
          pnpm --filter @pagopa/io-core-adapter-drizzle build
          pnpm --filter ced-portal-be build

      - name: Run migrations
        env:
          POSTGRES_HOST: ${{ secrets.CED_POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.CED_POSTGRES_PORT }}
          POSTGRES_USER: ${{ secrets.CED_POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.CED_POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.CED_POSTGRES_DB }}
        run: pnpm --filter ced-portal-be migrate:prod
