name: PR Infrastructure Plan CED

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "infra/resources/ced/**"
      - ".github/workflows/pr_infra_ced.yaml"

jobs:
  code_review_prod:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@main
    name: Code Review Infrastructure Plan CED
    secrets: inherit
    with:
      environment: prod
      base_path: infra/resources/ced
      override_github_environment: infra-prod
      use_private_agent: true