name: Renew Application Gateway Certs CED

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 2 1 * *'  # At 02:00 on day-of-month 1

jobs:

  renew-certificate:
    uses: pagopa/dx/.github/workflows/release-certificate-v1.yaml@main
    name: Create or Renew Certificate CED    
    secrets: inherit
    with:
      force_renewal: true
      key_vault_name: ced-p-itn-common-kv-01
      csr_common_name: api.ced.pagopa.it
      dns_zone: ced.pagopa.it
      dns_zone_resource_group: ced-p-itn-network-rg-01
      environment: infra-prod
