/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * CED Browser API
 * Public API for browsing and searching CED (Carta Europea della Disabilità) opportunities.
Citizens authenticated via IO App can consult and search opportunities available to them.

Only `published` opportunities within their valid date range (`date_from` ≤ today ≤ `date_to` or no expiry) are returned.

 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Citizen-facing full-text search on `place_materialized_view`.
Searches across place name, city, and operator profile display name.
Returns a flat list of places and operator profiles.
Requires citizen authentication (`Authorization: Bearer <token>`).

 * @summary Search places and operator profiles
 */
export const searchPlacesQueryQMin = 3;




export const SearchPlacesQueryParams = zod.object({
  "q": zod.string().min(searchPlacesQueryQMin).describe('Full-text search query (minimum 3 characters).'),
  "limit": zod.number().min(1).optional().describe('Maximum number of results to return (default 100).')
})

export const searchPlacesResponseTotalMin = 0;

export const searchPlacesResponseItemsItemUrlMax = 2048;



export const SearchPlacesResponse = zod.object({
  "total": zod.number().min(searchPlacesResponseTotalMin),
  "items": zod.array(zod.object({
  "id": zod.string().describe('place.id — always a place identifier.'),
  "name": zod.string().describe('COALESCE(profile.display_name, place.name) — shows the operator\'s\npublic name when the place is linked to the operator\'s profile.\n'),
  "entityId": zod.string().describe('operator.id — used by the FE to build navigation paths.'),
  "type": zod.enum(['place', 'profile']).describe('`profile` when the place is linked to the operator\'s profile (profile_id IS NOT NULL);\n`place` otherwise.\n'),
  "address": zod.object({
  "street": zod.string(),
  "city": zod.string(),
  "state": zod.string(),
  "postalCode": zod.string()
}).nullable().describe('Structured address. null for online places.'),
  "url": zod.url().max(searchPlacesResponseItemsItemUrlMax).optional().describe('Website URL. Present for online places only.')
}))
})

/**
 * Returns the full detail of a single place, including contact information,
associated published opportunities, and other places belonging to the same operator.
Requires citizen authentication (`Authorization: Bearer <token>`).

 * @summary Get place detail
 */
export const GetPlaceDetailParams = zod.object({
  "placeId": zod.string().describe('Place identifier.')
})

export const getPlaceDetailHeaderAcceptLanguageDefault = `it`;

export const GetPlaceDetailHeader = zod.object({
  "Accept-Language": zod.enum(['en', 'fr', 'de', 'sl', 'it']).default(getPlaceDetailHeaderAcceptLanguageDefault).describe('Language for opportunity titles (defaults to `it`). Must be an exact supported tag.')
})

export const GetPlaceDetailResponse = zod.object({
  "address": zod.object({
  "street": zod.string(),
  "city": zod.string(),
  "state": zod.string(),
  "postalCode": zod.string()
}).nullish().describe('Physical address. Null for online places.'),
  "contacts": zod.object({
  "phone": zod.string().optional().describe('Phone contact value, if available.'),
  "website": zod.url().optional().describe('Website contact URL, if available.')
}),
  "entityId": zod.string().describe('Operator identifier this place belongs to.'),
  "entityName": zod.string().describe('Operator display name.'),
  "id": zod.string().describe('Place identifier.'),
  "opportunities": zod.array(zod.object({
  "benefit": zod.object({
  "type": zod.enum(['free', 'reduced_fixed_price', 'priority', 'discount', 'other']).describe('Benefit type.'),
  "discountType": zod.enum(['percentage', 'fixed_amount']).nullish().describe('Discount calculation method. Present only when type is `discount`.'),
  "value": zod.number().nullish().describe('Numeric benefit value. Present when type is `reduced_fixed_price` or `discount`.')
}),
  "id": zod.string().describe('Opportunity identifier.'),
  "title": zod.string().describe('Opportunity title in the requested language.')
})).describe('Published opportunities redeemable at this place.'),
  "relatedPlaces": zod.array(zod.object({
  "address": zod.object({
  "street": zod.string(),
  "city": zod.string(),
  "state": zod.string(),
  "postalCode": zod.string()
}).nullish().describe('Address of the related place. Null for online places.'),
  "id": zod.string().describe('Related place identifier.'),
  "title": zod.string().describe('Display name of the related place.')
})).describe('Other places belonging to the same operator,\nordered alphabetically by name.\n'),
  "title": zod.string().describe('Place display name.')
})

